### ISSUE TITLE
Auth endpoint seems to have changed

### ISSUE THREAD

**Issue by clm42** [MattW224/ancestryDnaWrapper#1]
The authentication isn’t completing. Poking around it looks like the discoveryui-matches URL is still good.

**Comment by MattW224** [comment]
I believe the endpoint is correct, but when I initially developed this wrapper, I stumbled across a bizarre, implicit allow-listing process. In short, it involved a one-time call with very specific request headers, then all subsequent calls succeeded.

I'll retrace my steps, and update you here.

**Comment by MattW224** [comment]
The API calls (sample below) succeed from my desktop -- where I initially developed this script -- but fail (403 Forbidden) from an Amazon EC2 instance. Offhand, I don't know how to reconcile that disparity, but am recording some context here:

```
ancestry = ancestryDnaWrapper(username="foo", password="bar")
tests = ancestry.get_tests()

print(tests)
```

When I developed this, I copied the request headers from the Chrome developer console -- which resulted in consistent 403 errors. As a last ditch effort, I used [BurpSuite](https://portswigger.net/support/configuring-an-ios-device-to-work-with-burp) to intercept the request headers to the mobile endpoint. I wanted to see whether any delta existed between the desktop and mobile requests. When I copied those into my script, it suddenly started to work.

I duplicated that process on the EC2 instance today. It no longer overcomes this 403 error. I'll be looking more closely at how the [mobile app](https://apps.apple.com/us/app/ancestry-family-history-dna/id349554263) authenticates, and seeing if I can emulate that. If you have any suggestions, I'm all ears.

**Comment by clm42** [comment]
Did you adjust the user-agent for the EC2 instance? I'm on OSX (10.14.6, Python 3.7.4) and looking at the source its sending Windows headers. I'll see if I can assemble the OSX/Safari header and try that.

Update: Nope.

**Comment by MattW224** [comment]
I also tried [cloudscraper](https://github.com/VeNoMouS/cloudscraper) to no avail. The mobile app uses an https://auth.ancestry.com/ancauth/tokens endpoint, which requires a client secret token, and can't be emulated in my script. I'll continue researching, and keep you posted if I have a breakthrough.

**Comment by clm42** [comment]
I wonder if there is some hidden session cookie we are missing. I found where someone was going the scraping route with Selenium and they could auth from Python in January. Could be a case of Ancestry trying to block spiders. https://www.pythonfixing.com/2022/01/fixed-python-selenium-not-letting-me.html

also found someone on StackExchange trying to scrape with BeautifulSoup that references this script which uses requests to pull data. 

https://github.com/freeseek/getmydnamatches/blob/master/getmyancestrydna.py

**Comment by clm42** [comment]
Well it seems like Ancestry just hates OSX. I can pull my matches down with the script on a Windows computer. I get an error when trying to get shared matches but I'll open a separate issue for that.

**Comment by MattW224** [comment]
Face, meet palm.
