### ISSUE TITLE
Filter error when getting shared matches.

### ISSUE THREAD

**Issue by clm42** [MattW224/ancestryDnaWrapper#2]
When I try to get use `get_dna_matches()` it collects my matches fine. When iterate over those and  `get_dna_matches(shared_with_test_id = match['testGuid'])` I get the error `ValueError: Filters {'page', 'sortby', 'bookmarkData'} not accepted. See README for valid filter types.`

**Comment by MattW224** [comment]
ACK. This week is busy, but will look when I have availability.

**Comment by clm42** [comment]
Totally forgot about this, have you had a chance to look at it?

**Comment by MattW224** [comment]
Almost two years later -- revisiting this project, but haven't been able to reproduce this. Could you share your example, and I'll transpose the test IDs? If I don't receive a reply in a week, I'll close this issue.

**Comment by clm42** [comment]
That’s fine. I also have not had time to fool around with this. If I have a chance to tinker with it again one day I’ll let you know.
